In [ ]:
import numpy as np
import os
from PIL import Image

def load_images_and_labels(base_dir, class_labels):
    images = []
    labels = []

    for label, folder_name in class_labels.items():
        folder_path = os.path.join(base_dir, folder_name)
        for image_filename in os.listdir(folder_path):
            image_path = os.path.join(folder_path, image_filename)
            try:
                image = Image.open(image_path).convert('RGB')
                image_array = np.array(image)
                images.append(image_array)
                labels.append(label)
            except Exception as e:
                print(f"Błąd przy wczytywaniu obrazu {image_path}: {e}")

    return np.array(images), np.array(labels)

base_dir = '/content/drive/MyDrive/data'

class_labels = {
    1: 'moje',
    0: 'inne'
}

images, labels = load_images_and_labels(base_dir, class_labels)

print('Wczytano obrazy:', images.shape)
print('Wczytano etykiety:', labels.shape)

save_dir = '/content/drive/MyDrive/np_arrays'
if not os.path.exists(save_dir):
    os.makedirs(save_dir)

np.save(os.path.join(save_dir, 'images.npy'), images)
np.save(os.path.join(save_dir, 'labels.npy'), labels)
print('Zapisano obrazy i etykiety w:', save_dir)

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

path_to_images = '/content/drive/MyDrive/np_arrays/images.npy'
path_to_labels = '/content/drive/MyDrive/np_arrays/labels.npy'

images = np.load(path_to_images, mmap_mode='r')
labels = np.load(path_to_labels, mmap_mode='r')

X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Dropout
from sklearn.model_selection import train_test_split

model = Sequential([
    Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(200, 200, 3)),
    Conv2D(64, (3, 3), activation='relu'),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(2, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
history = model.fit(
    X_train, y_train,
    batch_size=16,
    epochs=30,
    validation_data=(X_test, y_test)
)

Epoch 1/30
284/284 [==============================] - 43s 124ms/step - loss: 93.4421 - accuracy: 0.9872 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 2/30
284/284 [==============================] - 33s 116ms/step - loss: 0.8563 - accuracy: 0.9993 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 3/30
284/284 [==============================] - 33s 117ms/step - loss: 231.2897 - accuracy: 0.9905 - val_loss: 0.3838 - val_accuracy: 0.9991
Epoch 4/30
284/284 [==============================] - 34s 118ms/step - loss: 45.3469 - accuracy: 0.9989 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 5/30
284/284 [==============================] - 33s 116ms/step - loss: 14.9754 - accuracy: 0.9993 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 6/30
284/284 [==============================] - 33s 117ms/step - loss: 88.0472 - accuracy: 0.9978 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 7/30
284/284 [==============================] - 33s 116ms/step - loss: 43.7927 - accuracy: 0.9982 

In [ ]:
model.fit(X_train, y_train, epochs=4, batch_size=16, verbose=0)

In [ ]:
results = model.evaluate(X_test, y_test)
print('Dokładność wytrenowanego modelu:')
print('\tEtykiety: ', model.metrics_names)
print('\tWartości: ', results)

36/36 [==============================] - 2s 25ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Dokładność wytrenowanego modelu:
	Etykiety:  ['loss', 'accuracy']
	Wartości:  [0.0, 1.0]


In [ ]:
model.save('/content/drive/MyDrive/model/wmapro4.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
print(X_train[0])

[[[ 34  29  31]
  [ 33  29  31]
  [ 34  30  32]
  ...
  [111 109 110]
  [112 110 111]
  [112 112 112]]

 [[ 34  30  32]
  [ 34  30  32]
  [ 34  30  32]
  ...
  [109 107 108]
  [112 110 111]
  [112 112 112]]

 [[ 34  30  32]
  [ 34  30  32]
  [ 34  30  32]
  ...
  [109 107 108]
  [112 110 111]
  [112 112 112]]

 ...

 [[ 19  11  14]
  [ 19  11  14]
  [ 19  11  14]
  ...
  [  8   4   4]
  [  8   4   4]
  [  7   3   3]]

 [[ 19  11  14]
  [ 19  11  14]
  [ 19  11  14]
  ...
  [  8   4   4]
  [  8   4   4]
  [  7   3   3]]

 [[ 19  11  14]
  [ 19  11  14]
  [ 19  11  14]
  ...
  [  9   5   5]
  [  9   5   5]
  [  8   4   4]]]
